"""
Tests for all file format parsers and the format detector.
Uses real in-memory file content — no disk I/O, no API calls.
"""

import os
import tempfile
import textwrap

from parsers.format_detector   import detect_format
from parsers.twentythreeme_parser import parse_23andme
from parsers.ancestry_parser   import parse_ancestry
from parsers.myheritage_parser import parse_myheritage
from parsers.vcf_parser        import parse_vcf
from parsers.normalizer        import normalize_variants


# ── Helpers ───────────────────────────────────────────────────────────────────
def _write_tmp(content: str, suffix: str) -> str:
    """Write a string to a temp file and return the path."""
    f = tempfile.NamedTemporaryFile(mode="w", suffix=suffix, delete=False)
    f.write(textwrap.dedent(content))
    f.flush()
    f.close()
    return f.name


# ─────────────────────────────────────────────────────────────────────────────
# 23andMe parser
# ─────────────────────────────────────────────────────────────────────────────
TWENTYTHREEME_CONTENT = """\
    # This data file generated by 23andMe at: Mon Jun 22 2026
    # This file contains raw genotype data, including data that is not used in 23andMe reports.
    # rsid\tchromosome\tposition\tgenotype
    rs4244285\t10\t96541616\tAG
    rs7903146\t10\t114758349\tCT
    rs12913832\t15\t28365618\tAG
    rs429358\t19\t44908684\tCT
    rs--\t1\t12345\tAA
"""


class TestTwentyThreeMeParser:
    def setup_method(self):
        self.path = _write_tmp(TWENTYTHREEME_CONTENT, ".txt")

    def teardown_method(self):
        os.unlink(self.path)

    def test_returns_list(self):
        variants = parse_23andme(self.path)
        assert isinstance(variants, list)

    def test_correct_count(self):
        variants = parse_23andme(self.path)
        # 5 data rows; rs-- is an invalid rsid and should be skipped
        assert len(variants) == 4

    def test_fields_present(self):
        v = parse_23andme(self.path)[0]
        assert "rsid"       in v
        assert "chromosome" in v
        assert "position"   in v
        assert "genotype"   in v

    def test_rsid_format(self):
        variants = parse_23andme(self.path)
        for v in variants:
            assert v["rsid"].startswith("rs")
            assert v["rsid"][2:].isdigit()

    def test_genotype_uppercase(self):
        variants = parse_23andme(self.path)
        for v in variants:
            assert v["genotype"] == v["genotype"].upper()

    def test_position_is_int(self):
        variants = parse_23andme(self.path)
        for v in variants:
            assert isinstance(v["position"], int)

    def test_comments_ignored(self):
        variants = parse_23andme(self.path)
        rsids = [v["rsid"] for v in variants]
        assert not any(r.startswith("#") for r in rsids)


# ─────────────────────────────────────────────────────────────────────────────
# AncestryDNA parser
# ─────────────────────────────────────────────────────────────────────────────
ANCESTRY_CONTENT = """\
    # AncestryDNA raw data download
    # This file was generated by Ancestry.
    rsid\tchromosome\tposition\tallele1\tallele2
    rs4244285\t10\t96541616\tA\tG
    rs7903146\t10\t114758349\tC\tT
    rs334\t11\t5246696\tA\tT
    rs1426654\t15\t48426484\tA\tG
"""


class TestAncestryParser:
    def setup_method(self):
        self.path = _write_tmp(ANCESTRY_CONTENT, ".txt")

    def teardown_method(self):
        os.unlink(self.path)

    def test_returns_list(self):
        assert isinstance(parse_ancestry(self.path), list)

    def test_correct_count(self):
        assert len(parse_ancestry(self.path)) == 4

    def test_alleles_present(self):
        v = parse_ancestry(self.path)[0]
        assert "allele1" in v
        assert "allele2" in v

    def test_genotype_concatenated(self):
        """AncestryDNA has separate allele columns; normalizer should concat them."""
        v = parse_ancestry(self.path)[0]
        # Parser may store allele1+allele2 or genotype — either is acceptable
        assert v.get("genotype") or (v.get("allele1") and v.get("allele2"))

    def test_header_row_not_included(self):
        variants = parse_ancestry(self.path)
        for v in variants:
            assert v["rsid"] != "rsid"


# ─────────────────────────────────────────────────────────────────────────────
# MyHeritage parser
# ─────────────────────────────────────────────────────────────────────────────
MYHERITAGE_CONTENT = """\
    ##MyHeritage DNA raw data file
    ##Download date: 2026-06-22
    RSID,CHROMOSOME,POSITION,RESULT
    rs4244285,10,96541616,AG
    rs7903146,10,114758349,CT
    rs12913832,15,28365618,AG
"""


class TestMyHeritageParser:
    def setup_method(self):
        self.path = _write_tmp(MYHERITAGE_CONTENT, ".csv")

    def teardown_method(self):
        os.unlink(self.path)

    def test_returns_list(self):
        assert isinstance(parse_myheritage(self.path), list)

    def test_correct_count(self):
        assert len(parse_myheritage(self.path)) == 3

    def test_rsid_present(self):
        for v in parse_myheritage(self.path):
            assert "rsid" in v

    def test_meta_comments_skipped(self):
        variants = parse_myheritage(self.path)
        for v in variants:
            assert not v["rsid"].startswith("#")
            assert not v["rsid"].startswith("RSID")


# ─────────────────────────────────────────────────────────────────────────────
# VCF parser
# ─────────────────────────────────────────────────────────────────────────────
VCF_CONTENT = """\
    ##fileformat=VCFv4.2
    ##reference=GRCh37
    ##FILTER=<ID=PASS,Description="All filters passed">
    #CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE
    10\t96541616\trs4244285\tG\tA\t.\tPASS\t.\tGT\t0/1
    10\t114758349\trs7903146\tC\tT\t.\tPASS\t.\tGT\t0/1
    19\t44908684\trs429358\tT\tC\t.\tPASS\t.\tGT\t0/1
    11\t5246696\t.\tA\tT\t.\tPASS\t.\tGT\t1/1
"""


class TestVcfParser:
    def setup_method(self):
        self.path = _write_tmp(VCF_CONTENT, ".vcf")

    def teardown_method(self):
        os.unlink(self.path)

    def test_returns_list(self):
        assert isinstance(parse_vcf(self.path), list)

    def test_skips_meta_lines(self):
        variants = parse_vcf(self.path)
        for v in variants:
            assert not str(v.get("rsid", "")).startswith("#")
            assert not str(v.get("rsid", "")).startswith("CHROM")

    def test_rsid_extracted_from_id_column(self):
        variants = parse_vcf(self.path)
        rsids = [v["rsid"] for v in variants if v.get("rsid", "").startswith("rs")]
        assert len(rsids) >= 3

    def test_position_numeric(self):
        for v in parse_vcf(self.path):
            assert isinstance(v["position"], int)


# ─────────────────────────────────────────────────────────────────────────────
# Format detector
# ─────────────────────────────────────────────────────────────────────────────
class TestFormatDetector:
    def test_detects_23andme(self):
        path = _write_tmp(TWENTYTHREEME_CONTENT, ".txt")
        try:
            assert detect_format(path) == "23andme"
        finally:
            os.unlink(path)

    def test_detects_ancestry(self):
        path = _write_tmp(ANCESTRY_CONTENT, ".txt")
        try:
            fmt = detect_format(path)
            assert fmt in ("ancestry", "23andme")  # both .txt; header distinguishes
        finally:
            os.unlink(path)

    def test_detects_myheritage(self):
        path = _write_tmp(MYHERITAGE_CONTENT, ".csv")
        try:
            assert detect_format(path) == "myheritage"
        finally:
            os.unlink(path)

    def test_detects_vcf(self):
        path = _write_tmp(VCF_CONTENT, ".vcf")
        try:
            assert detect_format(path) == "vcf"
        finally:
            os.unlink(path)

    def test_unknown_returns_unknown(self):
        path = _write_tmp("this is not a dna file\n", ".txt")
        try:
            result = detect_format(path)
            assert result == "unknown"
        finally:
            os.unlink(path)


# ─────────────────────────────────────────────────────────────────────────────
# Normalizer
# ─────────────────────────────────────────────────────────────────────────────
class TestNormalizer:
    def test_output_is_list(self, minimal_variants):
        result = normalize_variants(minimal_variants)
        assert isinstance(result, list)

    def test_all_have_rsid(self, minimal_variants):
        result = normalize_variants(minimal_variants)
        for v in result:
            assert "rsid" in v and v["rsid"]

    def test_all_have_genotype(self, minimal_variants):
        result = normalize_variants(minimal_variants)
        for v in result:
            assert "genotype" in v

    def test_strips_invalid_rsids(self):
        bad = [{"rsid": "rs--", "chromosome": "1", "position": 123, "genotype": "AA"}]
        result = normalize_variants(bad)
        assert len(result) == 0

    def test_deduplicates_rsids(self):
        dupes = [
            {"rsid": "rs4244285", "chromosome": "10", "position": 96541616, "genotype": "AG"},
            {"rsid": "rs4244285", "chromosome": "10", "position": 96541616, "genotype": "AG"},
        ]
        result = normalize_variants(dupes)
        rsids = [v["rsid"] for v in result]
        assert len(rsids) == len(set(rsids))

    def test_empty_input_returns_empty(self):
        assert normalize_variants([]) == []
