"""
Automatic detection of raw DNA file formats.
Supports: 23andMe, AncestryDNA, MyHeritage, VCF
"""

import re
import os


SIGNATURES = {
    "23andme": [
        "# This data file generated by 23andMe",
        "# rsid\tchromosome\tposition\tgenotype",
        "# This file was generated by 23andMe",
    ],
    "ancestry": [
        "#AncestryDNA",
        "# AncestryDNA raw data download",
        "rsid\tchromosome\tposition\tallele1\tallele2",
    ],
    "myheritage": [
        "##MyHeritage",
        "# MyHeritage DNA raw data",
        "RSID,CHROMOSOME,POSITION,RESULT",
    ],
    "vcf": [
        "##fileformat=VCF",
        "##FORMAT=<",
        "#CHROM\tPOS\tID\tREF\tALT",
    ],
}


def detect_format(filepath: str) -> str:
    """
    Reads the first 50 lines of a file and returns one of:
    '23andme', 'ancestry', 'myheritage', 'vcf', or 'unknown'
    """
    ext = os.path.splitext(filepath)[1].lower()

    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            header_lines = [f.readline() for _ in range(50)]
    except Exception:
        return "unknown"

    header_text = "\n".join(header_lines).upper()

    # VCF check first (extension + content)
    if ext == ".vcf":
        for sig in SIGNATURES["vcf"]:
            if sig.upper() in header_text:
                return "vcf"
        return "vcf"  # trust the extension

    # Check content signatures
    for fmt, sigs in SIGNATURES.items():
        for sig in sigs:
            if sig.upper() in header_text:
                return fmt

    # Heuristic: look for column header patterns
    for line in header_lines:
        line_up = line.upper().strip()
        if re.search(r"RSID.*CHROMOSOME.*POSITION.*ALLELE", line_up):
            # ancestry uses allele1/allele2
            if "ALLELE1" in line_up:
                return "ancestry"
            return "23andme"
        if re.search(r"RSID,CHROMOSOME,POSITION,RESULT", line_up):
            return "myheritage"

    return "unknown"
